### ISSUE TITLE
Associate more strongly abstract types and their canonical forms

### ISSUE THREAD

**Issue by giovinazzo-kevin** [G3Kappa/Ergo#15]
Abstract types are working, but it's clear that they're still not a definitive improvement over the previous system.

Specifically, it seems that terms that are obtained via unification are not always converted back to their abstract form because either operand is not recognized as an abstract term. Also, terms that are written directly in canonical form have the same issue.

Extending the abstract parsers to consider canonical forms is not guaranteed to work in scenarios where unification is the culprit, although it would solve some problems.

The previous system, and to a degree the current one, made extensive use of _term unfolding_, i.e. manually unwrapping the AST in order to reconstruct the abstract form. This is fine if it's guaranteed to happen once per term because terms are immutable, but there's currently no cache to keep track of these things and therefore it's a very expensive operation. Still, a cache feels like a band-aid. A better solution could be lurking in the shadows. 

Also, some results of unification could be represented more efficiently than they currently are: for instance, sub-lists could be represented as slices of a parent list.

**Comment by G3Kappa** [comment]
> > Also, some results of unification could be represented more efficiently than they currently are: for instance, sub-lists could be represented as slices of a parent list.
> 
> This remains an open point.

Good point. This should be its own issue though, past me.

**Comment by G3Kappa** [comment]
The cache was removed by #69 btw, which is a much cleaner solution overall
